[workspace]
resolver = "2"
members = [
    "components/as-keyvalue",
    "components/dep-cli",
    "components/ops",
    "components/sample-http-incrementor",
]

[workspace.package]
version = "0.3.0-dev"

[workspace.dependencies]
wit-bindgen = "0.61.0"

[profile.release]
opt-level = "s"
lto = true
codegen-units = 1
strip = "debuginfo"
