package componentized:valkey-components;

world cli {
    include wasi:cli/imports@0.2.6;
    import componentized:valkey/store@0.3.0-dev;
}

world valkey-ops {
    include wasi:sockets/imports@0.2.6;
    export componentized:valkey/resp@0.3.0-dev;
    export componentized:valkey/store@0.3.0-dev;
}

world as-keyvalue {
    import componentized:valkey/store@0.3.0-dev;
    import wasi:config/store@0.2.0-rc.1;
    export wasi:keyvalue/store@0.2.0-draft2;
    export wasi:keyvalue/atomics@0.2.0-draft2;
    export wasi:keyvalue/batch@0.2.0-draft2;
}

world sample-http-incrementor {
    import wasi:keyvalue/store@0.2.0-draft2;
    import wasi:keyvalue/atomics@0.2.0-draft2;
    export wasi:http/incoming-handler@0.2.6;
}
