interface store {
    use wasi:clocks/system-clock@0.3.0.{ duration, instant };
    use resp.{error as resp-error, value};

    variant error {
        /// Client errors can represent semantic issues with input/output values, or connection errors communicating with the server
        client(string),
        /// RESP errors are encoding issues converting values to/from bytes
        resp(resp-error),
        /// Valkey errors are Error or BulkError values returned directly from the server
        valkey(string),
    }

    enum expire-mode {
        /// Set expiration only when the field has no expiration.
        nx,
        /// Set expiration only when the field has an existing expiration.
        xx,
        /// Set expiration only when the new expiration is greater than current one.
        gt,
        /// Set expiration only when the new expiration is less than current one.
        lt,
    }

    enum expire-result {
        /// -2: key does not exist, or field does not exist in the HASH.
        does-not-exist,
        /// 0: the specified NX | XX | GT | LT condition has not been met.
        condition-not-met,
        /// 1: the expiration time was applied.
        applied,
        /// 2: when called with 0 seconds.
        zero-seconds,
    }

    record hello-opts {
        proto-ver: option<string>,
        auth: option<tuple<string, string>>,
        client-name: option<string>,
    }

    record hrandfield-opts {
        count: option<s64>,
        with-values: option<bool>,
    }

    record hscan-opts {
        match: option<string>,
        count: option<s64>,
        no-values: option<bool>,
    }

    resource connection {
        send: async func(command: list<value>) -> result<value, error>;

        acl-deluser: async func(username: string) -> result<_, error>;
        acl-genpass: async func() -> result<string, error>;
        acl-setuser: async func(username: string, rules: list<string>) -> result<_, error>;
        auth: async func(username: string, password: string) -> result<_, error>;
        del: async func(key: string) -> result<_, error>;
        exists: async func(key: string) -> result<bool, error>;
        expire: async func(key: string, seconds: duration, mode: option<expire-mode>) -> result<expire-result, error>;
        expireat: async func(key: string, seconds: instant, mode: option<expire-mode>) -> result<expire-result, error>;
        get: async func(key: string) -> result<option<string>, error>;
        hdel: async func(key: string, field: string) -> result<_, error>;
        hello: async func(opts: option<hello-opts>) -> result<list<tuple<string, value>>, error>;
        hexists: async func(key: string, field: string) -> result<bool, error>;
        hexpire: async func(key: string, seconds: duration, mode: option<expire-mode>, fields: list<string>) -> result<list<expire-result>, error>;
        hexpireat: async func(key: string, seconds: instant, mode: option<expire-mode>, fields: list<string>) -> result<list<expire-result>, error>;
        hget: async func(key: string, field: string) -> result<option<string>, error>;
        hgetall: async func(key: string) -> result<list<tuple<string, string>>, error>;
        hincrby: async func(key: string, field: string, increment: s64) -> result<s64, error>;
        hincrbyfloat: async func(key: string, field: string, increment: f64) -> result<string, error>;
        hkeys: async func(key: string) -> result<list<string>, error>;
        hlen: async func(key: string) -> result<u64, error>;
        hmget: async func(key: string, fields: list<string>) -> result<list<option<string>>, error>;
        hmset: async func(key: string, fields: list<tuple<string, string>>) -> result<_, error>;
        hrandfield: async func(key: string, opts: option<hrandfield-opts>) -> result<option<list<tuple<string, option<string>>>>, error>;
        hscan: async func(key: string, cursor: option<string>, opts: option<hscan-opts>) -> result<tuple<option<string>, list<tuple<string, option<string>>>>, error>;
        hset: async func(key: string, field: string, value: string) -> result<_, error>;
        hsetnx: async func(key: string, field: string, value: string) -> result<bool, error>;
        hstrlen: async func(key: string, field: string) -> result<u64, error>;
        hvals: async func(key: string) -> result<list<string>, error>;
        incr: async func(key: string) -> result<s64, error>;
        incrby: async func(key: string, increment: s64) -> result<s64, error>;
        keys: async func(pattern: string) -> result<list<string>, error>;
        ping: async func() -> result<_, error>;
        publish: async func(channel: string, message: string) -> result<s64, error>;
        quit: async func() -> result<_, error>;
        set: async func(key: string, value: string) -> result<_, error>;
    }

    connect: async func(host: string, port: u16, opts: option<hello-opts>) -> result<connection, error>;
}
